module.exports = [
  {id: 'XF96-0153', name: 'Alien Abductors', affiliation: 'alien', motive: 'knowledge', method: 'subterfuge', result: 'abduction'},
  {id: 'XF96-0141', name: 'Arctic Worm', affiliation: 'alien', motive: 'survival', method: 'possession', result: 'insanity'},
  {id: 'XF96-0152', name: 'Brother Martin', affiliation: 'alien', motive: 'knowledge', method: 'violence', result: 'death'},
  {id: 'XF96-0149', name: 'Alien Conservationist', affiliation: 'alien', motive: 'ideology', method: 'subterfuge', result: 'abduction'},
  {id: 'XF96-0147', name: 'Dod Kalm', affiliation: 'alien', motive: 'control', method: 'manipulation', result: 'physiological'},
  {id: 'XF96-0130', name: 'The Gregors', affiliation: 'alien', motive: 'security', method: 'manipulation', result: 'manipulation'},
  {id: 'XF96-0139', name: 'Alien Listeners', affiliation: 'alien', motive: 'ideology', method: 'subterfuge', result: 'manipulation'},
  {id: 'XF96-0155', name: 'Alien Experimenters', affiliation: 'alien', motive: 'survival', method: 'possession', result: 'death'},

  {id: 'XF96-0148', name: 'John Barnett', affiliation: 'government', motive: 'control', method: 'violence', result: 'death'},
  {id: 'XF96-0156', name: 'Reverse Engineers', affiliation: 'government', motive: 'security', method: 'threats', result: 'insanity'},
  {id: 'XF96-0140', name: 'Com. Colin Henderson', affiliation: 'government', motive: 'security', method: 'subterfuge', result: 'manipulation'},
  {id: 'XF96-0145', name: 'Ed Funsch, Postal Worker', affiliation: 'government', motive: 'control', method: 'possession', result: 'insanity'},
  {id: 'XF96-0122', name: 'Duane Barry', affiliation: 'government', motive: 'survival', method: 'violence', result: 'abduction'},
  {id: 'XF96-0150', name: 'Faciphaga Emasculata', affiliation: 'government', motive: 'knowledge', method: 'manipulation', result: 'physiological'},
  {id: 'XF96-0121', name: 'Cigarette-Smoking Man', affiliation: 'government', motive: 'ideology', method: 'threats', result: 'manipulation'},
  {id: 'XF96-0129', name: 'Alien DNA Steroid Prog.', affiliation: 'government', motive: 'knowledge', method: 'subterfuge', result: 'physiological'},

  {id: 'XF96-0136', name: 'Eugene Victor Tooms', affiliation: 'evolutionary', motive: 'survival', method: 'subterfuge', result: 'death'},
  {id: 'XF96-0133', name: 'Central Operating System,/AI', affiliation: 'evolutionary', motive: 'security', method: 'violence', result: 'manipulation'},
  {id: 'XF96-0154', name: 'Eve', affiliation: 'evolutionary', motive: 'knowledge', method: 'violence', result: 'abduction'},
  {id: 'XF96-0126', name: 'Arthur Grable', affiliation: 'evolutionary', motive: 'knowledge', method: 'possession', result: 'death'},
  {id: 'XF96-0124', name: 'The Host', affiliation: 'evolutionary', motive: 'survival', method: 'violence', result: 'physiological'},
  {id: 'XF96-0120', name: 'Augustus Cole', affiliation: 'evolutionary', motive: 'control', method: 'manipulation', result: 'death'},
  {id: 'XF96-0138', name: 'Dr. Banton', affiliation: 'evolutionary', motive: 'ideology', method: 'threats', result: 'manipulation'},
  {id: 'XF96-0158', name: 'Leonard, Cong. Twin', affiliation: 'evolutionary', motive: 'control', method: 'violence', result: 'death'},
  {id: 'XF96-0159', name: 'Cecil L\'ively', affiliation: 'evolutionary', motive: 'control', method: 'threats', result: 'death'},

  {id: 'XF96-0119', name: 'B.J. Morrow', affiliation: 'primordial', motive: 'control', method: 'possession', result: 'insanity'},
  {id: 'XF96-0123', name: 'The Jersey Devil', affiliation: 'primordial', motive: 'security', method: 'violence', result: 'death'},
  {id: 'XF96-0157', name: 'The Swarm', affiliation: 'primordial', motive: 'survival', method: 'violence', result: 'abduction'},
  {id: 'XF96-0134', name: 'Volcanic Spore', affiliation: 'primordial', motive: 'survival', method: 'manipulation', result: 'physiological'},
  {id: 'XF96-0125', name: 'Lucas Henry', affiliation: 'primordial', motive: 'control', method: 'violence', result: 'abduction'},
  {id: 'XF96-0143', name: 'Leonard Vance', affiliation: 'primordial', motive: 'knowledge', method: 'manipulation', result: 'physiological'},
  {id: 'XF96-0151', name: 'Donnie Pfaster', affiliation: 'primordial', motive: 'ideology', method: 'subterfuge', result: 'death'},
  {id: 'XF96-0131', name: 'Sheriff Tom Arens', affiliation: 'primordial', motive: 'ideology', method: 'subterfuge', result: 'insanity'},

  {id: 'XF96-0127', name: 'Warren James Dupre', affiliation: 'occult', motive: 'survival', method: 'possession', result: 'abduction'},
  {id: 'XF96-0142', name: 'The Manitou', affiliation: 'occult', motive: 'control', method: 'violence', result: 'death'},
  {id: 'XF96-0132', name: 'The Vampire', affiliation: 'occult', motive: 'survival', method: 'subterfuge', result: 'death'},
  {id: 'XF96-0144', name: 'Ancestor Spirits', affiliation: 'occult', motive: 'ideology', method: 'threats', result: 'physiological'},
  {id: 'XF96-0146', name: 'Mrs. Paddock', affiliation: 'occult', motive: 'ideology', method: 'threats', result: 'death'},
  {id: 'XF96-0128', name: 'Colonel Wharton', affiliation: 'occult', motive: 'knowledge', method: 'subterfuge', result: 'insanity'},
  {id: 'XF96-0135', name: 'Michael Holvey', affiliation: 'occult', motive: 'ideology', method: 'possession', result: 'physiological'},
  {id: 'XF96-0137', name: 'The Poltergeist', affiliation: 'occult', motive: 'security', method: 'threats', result: 'manipulation'},
];
